### PR TITLE
Guard against blank from

### LINKED ISSUE #234: [library_hours_rails/production] NoMethodError: undefined method `to_date' for nil:NilClass
Did you mean?  to_d
## Backtrace

    line 31 of [PROJECT_ROOT]/app/models/location.rb: business_days
    line 26 of [PROJECT_ROOT]/app/controllers/application_controller.rb: set_range
    line 11 of [PROJECT_ROOT]/app/controllers/locations_controller.rb: block in <class:LocationsController>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49891/faults/53166899)

### PR DESCRIPTION
**Pull request by cbeer**
Fixes #234

### CODE REVIEW

File: app/assets/config/manifest.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+//= link_tree ../images
+//= link application.js
+//= link application.css
```
Comment (jkeck) [inline app/assets/config/manifest.js:3]: Was this intended to be included in this PR?
